# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "787787a9c2d1daadd48dc2cb43fac2f4"
application_url = "https://indicating-handheld-bus-democracy.trycloudflare.com"
embedded = true
name = "Crossover Technologies"
handle = "crossover-technologies"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "https://golf-dev.xpos.co.uk/api/Shopify/MandatoryWebhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://spray-purse-erik-collection.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products,write_customers,write_inventory,write_locations,write_orders,write_products"

[auth]
redirect_urls = [
  "https://indicating-handheld-bus-democracy.trycloudflare.com/auth/callback",
  "https://indicating-handheld-bus-democracy.trycloudflare.com/auth/shopify/callback",
  "https://indicating-handheld-bus-democracy.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
